# Generated by Django 3.2.12 on 2023-11-10 20:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion', '0002_rename_profile_jugador'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jugador',
            new_name='Profile',
        ),
    ]
