# Generated by Django 5.0.2 on 2024-03-09 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_alter_maquinavulnerable_bandera_usuario_inicial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntuacionjugador',
            name='bandera',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='maquinavulnerable',
            name='bandera_usuario_inicial',
            field=models.CharField(default='a31dd9bcacc9e93e2e2827fe', max_length=25),
        ),
        migrations.AlterField(
            model_name='maquinavulnerable',
            name='bandera_usuario_root',
            field=models.CharField(default='584d1aae8b79284eb9ac44e0', max_length=25),
        ),
    ]
