# Generated by Django 3.2.12 on 2023-11-10 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_auto_20231110_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maquinavulnerable',
            name='identificador',
        ),
        migrations.CreateModel(
            name='AsociacionMaquinaJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activa', models.BooleanField(default=False)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.jugador')),
                ('maquina_vulnerable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.maquinavulnerable')),
            ],
        ),
    ]
