# Generated by Django 5.0.2 on 2024-03-10 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_alter_maquinavulnerable_bandera_usuario_inicial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquinavulnerable',
            name='bandera_usuario_inicial',
            field=models.CharField(default='07efa0737f6e25286cd6055f', max_length=25),
        ),
        migrations.AlterField(
            model_name='maquinavulnerable',
            name='bandera_usuario_root',
            field=models.CharField(default='ab7c8446333bdeb1a0dbfb30', max_length=25),
        ),
        migrations.AlterField(
            model_name='maquinavulnerable',
            name='nivel_dificultad',
            field=models.CharField(choices=[('Facil', 'Facil'), ('Media', 'Media'), ('Dificil', 'Dificil'), ('Experto', 'Experto')], max_length=10),
        ),
    ]
