# Generated by Django 3.2.12 on 2023-11-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_auto_20231110_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valoracionmaquina',
            name='jugador',
        ),
        migrations.RemoveField(
            model_name='valoracionmaquina',
            name='maquina',
        ),
        migrations.RenameField(
            model_name='jugador',
            old_name='usr',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='maquinavulnerable',
            old_name='nivel_minimo',
            new_name='nivel_minimo_activacion',
        ),
        migrations.RemoveField(
            model_name='maquinavulnerable',
            name='activa',
        ),
        migrations.AddField(
            model_name='jugador',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/'),
        ),
        migrations.AddField(
            model_name='jugador',
            name='nombre',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='puntuacion',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='maquinavulnerable',
            name='bandera_usuario_inicial',
            field=models.CharField(default='c7a32b11c645c573ec116f55', max_length=25),
        ),
        migrations.AlterField(
            model_name='maquinavulnerable',
            name='bandera_usuario_root',
            field=models.CharField(default='7e8f5bd0dc41da3b60f81915', max_length=25),
        ),
        migrations.AlterField(
            model_name='maquinavulnerable',
            name='nivel_dificultad',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='AsociacionMaquinaJugador',
        ),
        migrations.DeleteModel(
            name='ValoracionMaquina',
        ),
    ]
