# Generated by Django 5.0.2 on 2024-04-18 11:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_remove_jugador_puntuacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquinavulnerable',
            name='bandera_usuario_inicial',
            field=models.CharField(default='79afc2c80e91938b41001b76', max_length=25),
        ),
        migrations.AlterField(
            model_name='maquinavulnerable',
            name='bandera_usuario_root',
            field=models.CharField(default='ee1a9cd822071dbd3c2cd9b5', max_length=25),
        ),
        migrations.CreateModel(
            name='ValoracionJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valoracion', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('fecha_valoracion', models.DateTimeField(auto_now_add=True)),
                ('puntuacion_jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.puntuacionjugador')),
            ],
            options={
                'verbose_name_plural': 'Valoraciones de los jugadores',
            },
        ),
    ]
