# Generated by Django 5.0.2 on 2024-04-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_maquinajugador_tiempo_activa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquinajugador',
            name='momento_activacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='maquinavulnerable',
            name='bandera_usuario_inicial',
            field=models.CharField(default='2b2159ce491923e2732c0127', max_length=25),
        ),
        migrations.AlterField(
            model_name='maquinavulnerable',
            name='bandera_usuario_root',
            field=models.CharField(default='9912f59734088297695f4278', max_length=25),
        ),
    ]
