# Generated by Django 3.2.12 on 2023-11-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_auto_20231112_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquinavulnerable',
            name='bandera_usuario_inicial',
            field=models.CharField(default='aaf53f82bbe602db697c176b', max_length=25),
        ),
        migrations.AlterField(
            model_name='maquinavulnerable',
            name='bandera_usuario_root',
            field=models.CharField(default='62e63c2904c4d0ca11d19149', max_length=25),
        ),
        migrations.AlterField(
            model_name='maquinavulnerable',
            name='nivel_dificultad',
            field=models.CharField(choices=[('F', 'Facil'), ('M', 'Medio'), ('D', 'Dificil'), ('I', 'Insano')], max_length=1),
        ),
    ]
