# Generated by Django 5.0.2 on 2024-04-22 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_maquinajugador_momento_activacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquinajugador',
            name='tiempo_activa',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='maquinavulnerable',
            name='bandera_usuario_inicial',
            field=models.CharField(default='072ab26b2945db1e092d8a7b', max_length=25),
        ),
        migrations.AlterField(
            model_name='maquinavulnerable',
            name='bandera_usuario_root',
            field=models.CharField(default='62c25bce14249ac4a15c8e87', max_length=25),
        ),
    ]
