# Generated by Django 3.2.12 on 2023-11-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_auto_20231112_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquinavulnerable',
            name='bandera_usuario_inicial',
            field=models.CharField(default='d25853a46f94d2a77923b3c4', max_length=25),
        ),
        migrations.AlterField(
            model_name='maquinavulnerable',
            name='bandera_usuario_root',
            field=models.CharField(default='d5bb46d886769321ab35a936', max_length=25),
        ),
        migrations.AlterField(
            model_name='maquinavulnerable',
            name='nivel_dificultad',
            field=models.CharField(choices=[('Facil', 'Facil'), ('Medio', 'Medio'), ('Dificl', 'Dificil'), ('Insano', 'Insano')], max_length=6),
        ),
    ]
