# Generated by Django 3.2.12 on 2023-11-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_auto_20231112_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquinavulnerable',
            name='bandera_usuario_inicial',
            field=models.CharField(default='b51a3f6c0541f9b7ad1ba6a2', max_length=25),
        ),
        migrations.AlterField(
            model_name='maquinavulnerable',
            name='bandera_usuario_root',
            field=models.CharField(default='90d28a4729d1b1d7902bad12', max_length=25),
        ),
    ]
