# Generated by Django 5.0.2 on 2024-04-22 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_alter_maquinajugador_tiempo_activa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquinajugador',
            name='tiempo_activa',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='maquinavulnerable',
            name='bandera_usuario_inicial',
            field=models.CharField(default='1006be7bd71caea33cd291fb', max_length=25),
        ),
        migrations.AlterField(
            model_name='maquinavulnerable',
            name='bandera_usuario_root',
            field=models.CharField(default='68868662cc5d9ac3701432e7', max_length=25),
        ),
    ]
