# Generated by Django 5.0.2 on 2024-04-22 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_alter_maquinajugador_tiempo_activa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquinajugador',
            name='tiempo_activa',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maquinavulnerable',
            name='bandera_usuario_inicial',
            field=models.CharField(default='01bad837a1acc753d7c574f2', max_length=25),
        ),
        migrations.AlterField(
            model_name='maquinavulnerable',
            name='bandera_usuario_root',
            field=models.CharField(default='9318a7bfad6e8d892207929f', max_length=25),
        ),
    ]
