# Generated by Django 3.2.12 on 2023-11-12 11:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_auto_20231112_1148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maquinajugador',
            options={'verbose_name': 'Relacion jugadores con maquinas'},
        ),
        migrations.AlterField(
            model_name='jugador',
            name='nivel',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='maquinavulnerable',
            name='bandera_usuario_inicial',
            field=models.CharField(default='b885ba6f97a65b66fbfd790d', max_length=25),
        ),
        migrations.AlterField(
            model_name='maquinavulnerable',
            name='bandera_usuario_root',
            field=models.CharField(default='48c5da6ee058057047fc7641', max_length=25),
        ),
    ]
