# Generated by Django 3.2.12 on 2023-11-12 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0013_auto_20231112_1203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jugador',
            options={'verbose_name_plural': 'Jugadores'},
        ),
        migrations.AlterModelOptions(
            name='maquinajugador',
            options={'verbose_name_plural': 'Relaciones jugadores con maquinas'},
        ),
        migrations.AlterModelOptions(
            name='maquinavulnerable',
            options={'verbose_name_plural': 'Maquinas vulnerables'},
        ),
        migrations.AlterField(
            model_name='maquinavulnerable',
            name='bandera_usuario_inicial',
            field=models.CharField(default='6684ba376e9e642cf8570906', max_length=25),
        ),
        migrations.AlterField(
            model_name='maquinavulnerable',
            name='bandera_usuario_root',
            field=models.CharField(default='a52c9d4ed14803a242e0fc9c', max_length=25),
        ),
        migrations.AlterField(
            model_name='maquinavulnerable',
            name='nivel_minimo_activacion',
            field=models.IntegerField(default=1),
        ),
    ]
