# Generated by Django 3.2.12 on 2024-02-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0016_auto_20231112_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquinavulnerable',
            name='bandera_usuario_inicial',
            field=models.CharField(default='b75f0729706e83e957a587d5', max_length=25),
        ),
        migrations.AlterField(
            model_name='maquinavulnerable',
            name='bandera_usuario_root',
            field=models.CharField(default='5def0e6a9f24fb7cb878c3bf', max_length=25),
        ),
    ]
