# Generated by Django 3.2.12 on 2024-02-01 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0020_auto_20240201_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaquinaDockerCompose',
            fields=[
                ('maquinavulnerable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestion.maquinavulnerable')),
                ('ruta_archivo_docker_compose', models.CharField(max_length=255)),
                ('archivo', models.FileField(upload_to='archivos_zip/')),
            ],
            options={
                'verbose_name_plural': 'Maquinas Docker Compose',
            },
            bases=('gestion.maquinavulnerable',),
        ),
        migrations.CreateModel(
            name='MaquinaVirtual',
            fields=[
                ('maquinavulnerable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestion.maquinavulnerable')),
                ('ip_maquina_virtual', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name_plural': 'Maquinas Virtuales',
            },
            bases=('gestion.maquinavulnerable',),
        ),
        migrations.AlterField(
            model_name='maquinavulnerable',
            name='bandera_usuario_inicial',
            field=models.CharField(default='c3f3a7ae17643302cabd281d', max_length=25),
        ),
        migrations.AlterField(
            model_name='maquinavulnerable',
            name='bandera_usuario_root',
            field=models.CharField(default='4870c736d9a16da19efcb9b4', max_length=25),
        ),
    ]
