# Generated by Django 3.2.12 on 2024-02-01 18:29

from django.db import migrations, models
import gestion.functions


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0021_auto_20240201_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquinadockercompose',
            name='archivo',
            field=models.FileField(upload_to='maquinas_docker_compose/', validators=[gestion.functions.validate_zip_file]),
        ),
        migrations.AlterField(
            model_name='maquinavulnerable',
            name='bandera_usuario_inicial',
            field=models.CharField(default='9b2b6ffcee44672c641afbc3', max_length=25),
        ),
        migrations.AlterField(
            model_name='maquinavulnerable',
            name='bandera_usuario_root',
            field=models.CharField(default='7ed7a7ee4860f75dec1d850c', max_length=25),
        ),
    ]
