# Generated by Django 3.2.12 on 2024-02-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0025_auto_20240201_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquinadockercompose',
            name='ruta_archivo_docker_compose',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='maquinavulnerable',
            name='bandera_usuario_inicial',
            field=models.CharField(default='e7e45738264723d294c4b8a5', max_length=25),
        ),
        migrations.AlterField(
            model_name='maquinavulnerable',
            name='bandera_usuario_root',
            field=models.CharField(default='0a38fef6b84c8b9bbaf09f04', max_length=25),
        ),
    ]
