# Generated by Django 3.2.12 on 2024-02-01 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0026_auto_20240201_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maquinadockercompose',
            name='ruta_archivo_docker_compose',
        ),
        migrations.AlterField(
            model_name='maquinavulnerable',
            name='bandera_usuario_inicial',
            field=models.CharField(default='8cce50d395912c458c88453f', max_length=25),
        ),
        migrations.AlterField(
            model_name='maquinavulnerable',
            name='bandera_usuario_root',
            field=models.CharField(default='f90e671a7b753ac877670f64', max_length=25),
        ),
    ]
