# Generated by Django 3.2.12 on 2024-02-01 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0027_auto_20240202_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquinadockercompose',
            name='extracted_folder',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='maquinavulnerable',
            name='bandera_usuario_inicial',
            field=models.CharField(default='ea6c565556dcfdb655dd7a48', max_length=25),
        ),
        migrations.AlterField(
            model_name='maquinavulnerable',
            name='bandera_usuario_root',
            field=models.CharField(default='18cd95a8e964921b2abc7df1', max_length=25),
        ),
    ]
