# Generated by Django 3.2.12 on 2024-02-01 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0030_auto_20240202_0042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maquinadockercompose',
            name='extracted_folder',
        ),
        migrations.AlterField(
            model_name='maquinavulnerable',
            name='bandera_usuario_inicial',
            field=models.CharField(default='79ff087cbce26629367f197c', max_length=25),
        ),
        migrations.AlterField(
            model_name='maquinavulnerable',
            name='bandera_usuario_root',
            field=models.CharField(default='54dff7a84ca12ae3b625f155', max_length=25),
        ),
    ]
