# Generated by Django 3.2.12 on 2024-02-02 01:20

from django.db import migrations, models
import gestion.functions


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0031_auto_20240202_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquinadockercompose',
            name='archivo',
            field=models.FileField(upload_to='archivoZipDockerCompose/', validators=[gestion.functions.validate_zip_file]),
        ),
        migrations.AlterField(
            model_name='maquinavulnerable',
            name='bandera_usuario_inicial',
            field=models.CharField(default='4b4c4c8c2261cdfc65c43d1c', max_length=25),
        ),
        migrations.AlterField(
            model_name='maquinavulnerable',
            name='bandera_usuario_root',
            field=models.CharField(default='4fca9f92005ecb50a0efc20d', max_length=25),
        ),
    ]
