# Generated by Django 5.0.2 on 2024-02-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0034_maquinavulnerable_ip_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maquinavulnerable',
            name='ip_address',
        ),
        migrations.AddField(
            model_name='maquinajugador',
            name='ip_address',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='maquinavulnerable',
            name='bandera_usuario_inicial',
            field=models.CharField(default='3daa1e1ec344c7c633636cc1', max_length=25),
        ),
        migrations.AlterField(
            model_name='maquinavulnerable',
            name='bandera_usuario_root',
            field=models.CharField(default='1a4dbf4f195357d8f05d68df', max_length=25),
        ),
    ]
