# Generated by Django 5.0.2 on 2024-02-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0035_remove_maquinavulnerable_ip_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquinavulnerable',
            name='bandera_usuario_inicial',
            field=models.CharField(default='6e4f4dbc1b9c487d915015bb', max_length=25),
        ),
        migrations.AlterField(
            model_name='maquinavulnerable',
            name='bandera_usuario_root',
            field=models.CharField(default='bc03b4c70ebe1230041b6d01', max_length=25),
        ),
    ]
