# Generated by Django 5.0.2 on 2024-02-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0038_alter_maquinadockercompose_archivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquinavulnerable',
            name='bandera_usuario_inicial',
            field=models.CharField(default='154f0f3dd5215784e809c2b6', max_length=25),
        ),
        migrations.AlterField(
            model_name='maquinavulnerable',
            name='bandera_usuario_root',
            field=models.CharField(default='af604070c358ac1212de66ff', max_length=25),
        ),
    ]
