# Generated by Django 5.0.2 on 2024-02-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0039_alter_maquinavulnerable_bandera_usuario_inicial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquinavulnerable',
            name='bandera_usuario_inicial',
            field=models.CharField(default='803a50d3b9503052cb7b605d', max_length=25),
        ),
        migrations.AlterField(
            model_name='maquinavulnerable',
            name='bandera_usuario_root',
            field=models.CharField(default='e69f8e3c64618cff075f3f58', max_length=25),
        ),
    ]
