# Generated by Django 5.0.2 on 2024-02-22 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0042_persona_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona',
            options={'verbose_name_plural': 'Persona'},
        ),
        migrations.AlterField(
            model_name='maquinavulnerable',
            name='bandera_usuario_inicial',
            field=models.CharField(default='d30f9dd2ba244214b8ecd588', max_length=25),
        ),
        migrations.AlterField(
            model_name='maquinavulnerable',
            name='bandera_usuario_root',
            field=models.CharField(default='0aadb1ea16d32fc4b14cdc7d', max_length=25),
        ),
        migrations.AlterField(
            model_name='persona',
            name='edad',
            field=models.IntegerField(),
        ),
    ]
