# Generated by Django 5.0.2 on 2024-02-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0044_delete_persona_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maquinadocker',
            name='puerto_exposicion',
        ),
        migrations.AlterField(
            model_name='maquinavulnerable',
            name='bandera_usuario_inicial',
            field=models.CharField(default='53054ab407d0c0f878fabe6d', max_length=25),
        ),
        migrations.AlterField(
            model_name='maquinavulnerable',
            name='bandera_usuario_root',
            field=models.CharField(default='d45ee6cc1851ff9892f583e4', max_length=25),
        ),
    ]
