# Generated by Django 5.0.2 on 2024-02-29 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0049_alter_maquinavulnerable_bandera_usuario_inicial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquinavulnerable',
            name='bandera_usuario_inicial',
            field=models.CharField(default='dd5a78093eb71305f9899bfd', max_length=25),
        ),
        migrations.AlterField(
            model_name='maquinavulnerable',
            name='bandera_usuario_root',
            field=models.CharField(default='a7d73cfa568152459e0038c4', max_length=25),
        ),
    ]
