# Generated by Django 5.0.2 on 2024-03-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0053_maquinavulnerable_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugador',
            name='nivel',
        ),
        migrations.AlterField(
            model_name='maquinavulnerable',
            name='bandera_usuario_inicial',
            field=models.CharField(default='4069878e9ec6f0414ee2f57f', max_length=25),
        ),
        migrations.AlterField(
            model_name='maquinavulnerable',
            name='bandera_usuario_root',
            field=models.CharField(default='5268dd8388b576a650a182c7', max_length=25),
        ),
    ]
