# Generated by Django 5.0.2 on 2024-03-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0054_remove_jugador_nivel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquinavulnerable',
            name='bandera_usuario_inicial',
            field=models.CharField(default='3a507de23727be10f2c405d7', max_length=25),
        ),
        migrations.AlterField(
            model_name='maquinavulnerable',
            name='bandera_usuario_root',
            field=models.CharField(default='7e6eb44fcfac33fc44a1c793', max_length=25),
        ),
        migrations.AlterField(
            model_name='maquinavulnerable',
            name='nivel_dificultad',
            field=models.CharField(choices=[('Facil', 'Facil'), ('Medio', 'Medio'), ('Dificl', 'Dificil'), ('Bestia', 'Bestia')], max_length=6),
        ),
    ]
