# Generated by Django 5.0.2 on 2024-03-05 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0055_alter_maquinavulnerable_bandera_usuario_inicial_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maquinavulnerable',
            old_name='nivel_minimo_activacion',
            new_name='puntuacion_minima_activacion',
        ),
        migrations.AlterField(
            model_name='maquinavulnerable',
            name='bandera_usuario_inicial',
            field=models.CharField(default='157b3ca8d4d445eef8cebcb0', max_length=25),
        ),
        migrations.AlterField(
            model_name='maquinavulnerable',
            name='bandera_usuario_root',
            field=models.CharField(default='13929214c7e809fea4cef55d', max_length=25),
        ),
    ]
