# Generated by Django 5.0.2 on 2024-03-05 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0056_rename_nivel_minimo_activacion_maquinavulnerable_puntuacion_minima_activacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='photoPersonal/'),
        ),
        migrations.AlterField(
            model_name='maquinavulnerable',
            name='bandera_usuario_inicial',
            field=models.CharField(default='9f55774eb448da182de3f96d', max_length=25),
        ),
        migrations.AlterField(
            model_name='maquinavulnerable',
            name='bandera_usuario_root',
            field=models.CharField(default='120236e6fc4c06d0efc102be', max_length=25),
        ),
    ]
