# Generated by Django 5.0.2 on 2024-03-05 22:23

import gestion.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0058_alter_maquinavulnerable_bandera_usuario_inicial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='foto_perfil',
            field=models.ImageField(blank=True, default='photoPersonal/default.jpg', max_length=1000, null=True, storage=gestion.functions.OverwriteStorage(), upload_to='photoPersonal/'),
        ),
        migrations.AlterField(
            model_name='maquinavulnerable',
            name='bandera_usuario_inicial',
            field=models.CharField(default='72e8d6e5169ab7f62ce43282', max_length=25),
        ),
        migrations.AlterField(
            model_name='maquinavulnerable',
            name='bandera_usuario_root',
            field=models.CharField(default='dcc9444ee4297fb75c56a1cc', max_length=25),
        ),
    ]
