# Generated by Django 5.0.2 on 2024-03-06 18:00

import gestion.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0059_alter_jugador_foto_perfil_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maquinadocker',
            name='imagen_docker',
        ),
        migrations.AddField(
            model_name='maquinadocker',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='archivoZipDockerCompose/', validators=[gestion.functions.validate_zip_file]),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='foto_perfil',
            field=models.ImageField(blank=True, default='photoPersonal/default.jpg', null=True, storage=gestion.functions.OverwriteStorage(), upload_to='photoPersonal/'),
        ),
        migrations.AlterField(
            model_name='maquinavulnerable',
            name='bandera_usuario_inicial',
            field=models.CharField(default='d191dddd03111d6db9eda7a2', max_length=25),
        ),
        migrations.AlterField(
            model_name='maquinavulnerable',
            name='bandera_usuario_root',
            field=models.CharField(default='d98a68e69bc6f414add2b07d', max_length=25),
        ),
    ]
