# Generated by Django 5.0.2 on 2024-03-06 18:44

import gestion.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0060_remove_maquinadocker_imagen_docker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquinavulnerable',
            name='instrucciones',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='maquinadocker',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='archivoZipDocker/', validators=[gestion.functions.validate_zip_file]),
        ),
        migrations.AlterField(
            model_name='maquinavulnerable',
            name='bandera_usuario_inicial',
            field=models.CharField(default='e08802cb840603eead32dc18', max_length=25),
        ),
        migrations.AlterField(
            model_name='maquinavulnerable',
            name='bandera_usuario_root',
            field=models.CharField(default='cb23b4481d1405601ee29a6d', max_length=25),
        ),
    ]
