# Generated by Django 5.0.2 on 2024-03-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0061_maquinavulnerable_instrucciones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquinavulnerable',
            name='bandera_usuario_inicial',
            field=models.CharField(default='673ba14e21726c5e31991c22', max_length=25),
        ),
        migrations.AlterField(
            model_name='maquinavulnerable',
            name='bandera_usuario_root',
            field=models.CharField(default='da00ecab94fc91a67909566b', max_length=25),
        ),
    ]
